### PR TITLE
models: add `Group` for altering table `radusergroup`

### LINKED ISSUE #13: 创建RADIUS用户时，将用户添加到用户组
(Moved From GitLab)
改进：创建RADIUS用户时，将用户添加到用户组
SQL语句举例： INSERT INTO radusergroup (UserName, GroupName, priority) VALUES ('zzh1996', 'groupname', 1);
这样就可以利用用户组来批量为用户添加流量限制和连接数限制

### PR DESCRIPTION
**Pull request by knight42**
Fix #13

### CODE REVIEW

**Comment by knight42** [comment]
cc @gaoyifan @zzh1996

**Comment by gaoyifan** [comment]
maybe we need a script to migrate existed users

**Comment by knight42** [comment]
A simple for loop should be sufficient, i.e.

```
for i in VPNAccount.query:
    Group(i.username).save()
```

Already imported existing users now.

**Comment by zzh1996** [comment]
```
truncate radusergroup;
insert into radusergroup select distinct email,'normal',1 from user where status='pass';
```

**Pull request merged**
